import 'dotenv/config'
import mongoose from 'mongoose'
import { connectDatabase } from '../src/config/database.js'
import Brand from '../src/models/Brand.js'
import Category from '../src/models/Category.js'
import Attribute from '../src/models/Attribute.js'
import Product from '../src/models/product.model.js'
const sources={nike:'https://www.nike.com/',adidas:'https://www.adidas.com/',levis:'https://www.levi.com/',uniqlo:'https://www.uniqlo.com/',zara:'https://www.zara.com/',hm:'https://www2.hm.com/',nb:'https://www.newbalance.com/',puma:'https://us.puma.com/'}
const brands=[['Nike','nike'],['adidas','adidas'],["Levi's",'levis'],['UNIQLO','uniqlo'],['ZARA','zara'],['H&M','hm'],['New Balance','new-balance'],['PUMA','puma']]
const categories=[['Ao thun','ao-thun'],['Hoodie & Sweatshirt','hoodie-sweatshirt'],['Ao khoac','ao-khoac'],['Quan jeans','quan-jeans'],['Quan tay & Kaki','quan-tay-kaki'],['Dam','dam'],['Giay sneaker','giay-sneaker'],['Tui xach','tui-xach'],['Do the thao','do-the-thao'],['Phu kien','phu-kien']]
const colors=[['Den','den','#111111'],['Trang','trang','#FFFFFF'],['Xanh navy','xanh-navy','#172B4D'],['Be','be','#C9B79C'],['Do','do','#A61B1B']]
const categoryImages={'giay-sneaker':['https://images.unsplash.com/photo-1542291026-7eec264c27ff','https://images.unsplash.com/photo-1600185365483-26d7a4cc7519','https://images.unsplash.com/photo-1549298916-b41d501d3772','https://images.unsplash.com/photo-1552346154-21d32810aba3','https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77'],'quan-jeans':['https://images.unsplash.com/photo-1542272604-787c3835535d','https://images.unsplash.com/photo-1582552938357-32b906df40cb','https://images.unsplash.com/photo-1541099649105-f69ad21f3246','https://images.unsplash.com/photo-1475178626620-a4d074967452','https://images.unsplash.com/photo-1517841905240-472988babdf9'],'tui-xach':['https://images.unsplash.com/photo-1553062407-98eeb64c6a62','https://images.unsplash.com/photo-1584917865442-de89df76afd3','https://images.unsplash.com/photo-1594223274512-ad4803739b7c','https://images.unsplash.com/photo-1548036328-c9fa89d128fa','https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d'],'dam':['https://images.unsplash.com/photo-1595777457583-95e059d581b8','https://images.unsplash.com/photo-1566174053879-31528523f8ae','https://images.unsplash.com/photo-1572804013309-59a88b7e92f1','https://images.unsplash.com/photo-1539008835657-9e8e9680c956','https://images.unsplash.com/photo-1585488431767-6d3f7c9b1c43'],'ao-thun':['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab','https://images.unsplash.com/photo-1503341504253-dff4815485f1','https://images.unsplash.com/photo-1583743814966-8936f37f4f7d','https://images.unsplash.com/photo-1562157873-818bc0726f68','https://images.unsplash.com/photo-1551488831-00ddcb6cbd3']};
const colorImages={den:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&h=1200&q=82',trang:'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&h=1200&q=82','xanh-navy':'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&h=1200&q=82',be:'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=900&h=1200&q=82',do:'https://images.unsplash.com/photo-1551488831-00ddcb6cbd3?auto=format&fit=crop&w=900&h=1200&q=82'}
const sizeSets={'giay-sneaker':['38','39','40','41','42'],'tui-xach':['Small','Large'],dam:['S','M','L','XL'],'ao-thun':['S','M','L','XL'],'hoodie-sweatshirt':['S','M','L','XL'],'ao-khoac':['S','M','L','XL'],'quan-jeans':['29','30','31','32','33'],'quan-tay-kaki':['29','30','31','32','33'],'do-the-thao':['S','M','L','XL'],'phu-kien':['Small','Large']}
const families=[["Giày Air Force 1 07",'nike','giay-sneaker',2990000,'CW2288','nike'],['Giày Samba OG','adidas','giay-sneaker',2090000,'SAMBA','adidas'],['Quần jeans 501 dáng nguyên bản','levis','quan-jeans',2190000,'00501','levis'],['Áo thun cotton AIRism','uniqlo','ao-thun',499000,'AIRISM','uniqlo'],['Áo hoodie nỉ Club Fleece','nike','hoodie-sweatshirt',1590000,'FLEECE','nike'],['Áo thun cotton Essential','zara','ao-thun',399000,'ZARA-TEE','zara'],['Áo thun dáng cơ bản','hm','ao-thun',299000,'HM-TEE','hm'],['Giày 574 cổ điển','new-balance','giay-sneaker',2490000,'U574','nb'],['Giày Suede Classic XXI','puma','giay-sneaker',1890000,'PUMA-SUEDE','puma'],['Áo thể thao Dri-FIT Academy','nike','do-the-thao',890000,'DRIFIT','nike'],['Áo thun 3 sọc Essentials','adidas','ao-thun',690000,'3STRIPES','adidas'],['Quần tây Smart Ankle','uniqlo','quan-tay-kaki',799000,'ANKLE','uniqlo'],['Áo blazer dáng rộng','zara','ao-khoac',1990000,'BLAZER','zara'],['Áo sơ mi linen pha','hm','ao-thun',699000,'LINEN','hm'],['Quần jeans 511 dáng ôm','levis','quan-jeans',1990000,'04511','levis'],['Áo khoác Windrunner','nike','ao-khoac',1890000,'WINDRUNNER','nike'],['Áo khoác thể thao Firebird','adidas','ao-khoac',1790000,'FIREBIRD','adidas'],['Đầm midi satin','zara','dam',1590000,'SATIN','zara'],['Đầm hai dây','hm','dam',799000,'SLIP','hm'],['Túi đeo vai mini','uniqlo','tui-xach',499000,'SHOULDER','uniqlo'],['Áo phao Essential','uniqlo','ao-khoac',1890000,'PUFFER','uniqlo'],['Quần cargo dáng rộng','zara','quan-tay-kaki',1290000,'CARGO','zara'],['Giày Campus 00s','adidas','giay-sneaker',2290000,'CAMPUS','adidas'],['Giày 530 Lifestyle','new-balance','giay-sneaker',2790000,'U530','nb'],['Ba lô Essentials','puma','phu-kien',899000,'BACKPACK','puma']]
const suffixes=['Cổ điển','Dáng thư giãn','Dòng studio','Thiết yếu']
const slugify=(v)=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const upsert=(Model,filter,data)=>Model.findOneAndUpdate(filter,{$set:data},{upsert:true,new:true,setDefaultsOnInsert:true})
try{
 await connectDatabase(); await Promise.all([Product.deleteMany({}),Brand.deleteMany({}),Category.deleteMany({}),Attribute.deleteMany({})])
 const brandDocs=new Map((await Promise.all(brands.map(([name,slug])=>upsert(Brand,{slug},{name,slug,description:'Danh mục chính hãng của '+name,is_deleted:false,deletedAt:null})))).map(d=>[d.slug,d]))
 const categoryDocs=new Map((await Promise.all(categories.map(([name,slug])=>upsert(Category,{slug},{name,slug,description:'Danh mục '+name,is_deleted:false,deletedAt:null})))).map(d=>[d.slug,d]))
 const colorAttribute=await upsert(Attribute,{slug:'mau-sac'},{name:'Màu sắc',slug:'mau-sac',display_type:'color',values:colors.map(([name,slug,color_hex])=>({name,slug,color_hex,is_deleted:false})),is_deleted:false})
 const sizeAttribute=await upsert(Attribute,{slug:'kich-thuoc'},{name:'Kích thước',slug:'kich-thuoc',display_type:'text',values:[...new Set(Object.values(sizeSets).flat())].map(name=>({name,slug:slugify(name),is_deleted:false})),is_deleted:false})
 const docs=[]
 families.forEach(([model,brandSlug,categorySlug,price,code,sourceKey],familyIndex)=>suffixes.forEach((suffix,suffixIndex)=>{
  const name=model+' '+suffix; const sizes=sizeSets[categorySlug]; const assets=colors.map(([,slug],colorIndex)=>({_id:new mongoose.Types.ObjectId(),url:(categoryImages[categorySlug] || categoryImages['ao-thun'])[colorIndex]+'?auto=format&fit=crop&w=900&h=1200&q=85',public_id:null}))
  const variants=colors.flatMap(([colorName,colorSlug,colorHex],colorIndex)=>sizes.map((size,sizeIndex)=>{
   const cv=colorAttribute.values.find(v=>v.slug===colorSlug); const sv=sizeAttribute.values.find(v=>v.slug===slugify(size)); const bp=price+((colorIndex+sizeIndex+suffixIndex)%3)*10000
   return {sku:code+'-'+(familyIndex+1)+'-'+(suffixIndex+1)+'-'+colorSlug.toUpperCase()+'-'+slugify(size).toUpperCase(),stock:6+((colorIndex+sizeIndex)%12),base_price:bp,sale_price:(colorIndex+sizeIndex+familyIndex)%7===0?Math.round(bp*.9):null,color:colorName,size,option_values:[{attribute_id:colorAttribute._id,value_id:cv._id,attribute_name:colorAttribute.name,attribute_slug:colorAttribute.slug,value_name:cv.name,value_slug:cv.slug,color_hex:colorHex},{attribute_id:sizeAttribute._id,value_id:sv._id,attribute_name:sizeAttribute.name,attribute_slug:sizeAttribute.slug,value_name:sv.name,value_slug:sv.slug,color_hex:null}],image_asset_ids:[assets[colorIndex]._id]}
  }))
  docs.push({name,brand_id:brandDocs.get(brandSlug)._id,brand:brandDocs.get(brandSlug).name,category_id:categoryDocs.get(categorySlug)._id,description:'Sản phẩm '+name+' thuộc thương hiệu '+brandDocs.get(brandSlug).name+'. Tham khảo: '+sources[sourceKey],base_price:price,sale_price:null,images:assets.map(a=>a.url),image_assets:assets,gallery_asset_ids:assets.map(a=>a._id),option_axes:[{attribute_id:colorAttribute._id,attribute_name:colorAttribute.name,attribute_slug:colorAttribute.slug,value_ids:colorAttribute.values.map(v=>v._id)},{attribute_id:sizeAttribute._id,attribute_name:sizeAttribute.name,attribute_slug:sizeAttribute.slug,value_ids:sizes.map(s=>sizeAttribute.values.find(v=>v.slug===slugify(s))._id)}],variants,business_enabled:true,is_deleted:false,deletedAt:null,embedding_vector:[]})
 }))
 await Product.insertMany(docs); console.log('Seed complete: '+docs.length+' parent products, '+docs.reduce((s,p)=>s+p.variants.length,0)+' variants, '+brandDocs.size+' brands, '+categoryDocs.size+' categories')
}finally{await mongoose.disconnect()}