import { ImagePlus, Plus, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { saveAdminProduct } from '../../../services/adminProductApi.js'

const cleanSku = (value) => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase().replace(/[^A-Z0-9]+/g, '-').replace(/^-|-$/g, '')
const legacyVariant = (variant = {}) => ({ sku: variant.sku || '', option_values: variant.option_values || [], color: variant.color || '', size: variant.size || '', stock: variant.stock ?? 0, base_price: variant.base_price ?? '', sale_price: variant.sale_price ?? '', image_asset_ids: (variant.image_asset_ids || []).map(String) })
const optionKey = (values = []) => values.map((value) => `${value.attribute_id}:${value.value_id}`).sort().join('|')
function combinations(axes, attributes) {
  let rows = [[]]
  for (const axis of axes) { const attribute = attributes.find((item) => item._id === axis.attribute_id); const values = (axis.value_ids || []).map((id) => attribute?.values.find((value) => value._id === id)).filter(Boolean); rows = rows.flatMap((row) => values.map((value) => [...row, { attribute_id: attribute._id, value_id: value._id, attribute_slug: attribute.slug, value_slug: value.slug, value_name: value.name }])) }
  return rows
}

export default function AdminProductDrawer({ product, categories, brands, attributes, onClose, onSaved }) {
  const [form, setForm] = useState(() => ({ name: product?.name || '', brand_id: product?.brand_id?._id || product?.brand_id || '', description: product?.description || '', category_id: product?.category_id?._id || product?.category_id || '', base_price: product?.base_price ?? '', sale_price: product?.sale_price ?? '', business_enabled: product?.business_enabled ?? true, option_axes: (product?.option_axes || []).map((axis) => ({ attribute_id: String(axis.attribute_id), value_ids: axis.value_ids.map(String) })), variants: product?.variants?.length ? product.variants.map(legacyVariant) : [{ ...legacyVariant(), sku: '' }] }))
  const [images, setImages] = useState(() => (product?.image_assets?.length ? product.image_assets : (product?.images || []).map((url) => ({ url }))).map((asset) => ({ type: 'existing', id: String(asset._id || asset.url), url: asset.url, file: null })))
  const [gallery, setGallery] = useState(() => (product?.gallery_asset_ids?.length ? product.gallery_asset_ids.map(String) : (product?.image_assets || []).slice(0, 5).map((asset) => String(asset._id))))
  const [busy, setBusy] = useState(false), [error, setError] = useState('')
  const newFiles = useMemo(() => images.filter((image) => image.type === 'new').map((image) => image.file), [images])
  const field = (name) => (event) => setForm((current) => ({ ...current, [name]: event.target.type === 'checkbox' ? event.target.checked : event.target.value }))
  const refOf = (image) => image.type === 'new' ? `new:${images.filter((item) => item.type === 'new').indexOf(image)}` : image.id
  const setAxisAttribute = (index, attributeId) => setForm((current) => ({ ...current, option_axes: current.option_axes.map((axis, position) => position === index ? { attribute_id: attributeId, value_ids: [] } : axis) }))
  const toggleAxisValue = (index, valueId) => setForm((current) => ({ ...current, option_axes: current.option_axes.map((axis, position) => position === index ? { ...axis, value_ids: axis.value_ids.includes(valueId) ? axis.value_ids.filter((id) => id !== valueId) : [...axis.value_ids, valueId] } : axis) }))
  const generate = () => {
    if (!form.option_axes.length || form.option_axes.some((axis) => !axis.attribute_id || !axis.value_ids.length)) return setError('Mỗi nhóm thuộc tính phải có ít nhất một giá trị')
    const combos = combinations(form.option_axes, attributes); if (combos.length > 100) return setError('Tối đa 100 tổ hợp cho mỗi sản phẩm')
    const old = new Map(form.variants.map((variant) => [optionKey(variant.option_values), variant])); const prefix = cleanSku(form.name).split('-').map((part) => part[0]).join('').slice(0, 8) || 'SP'
    setForm((current) => ({ ...current, variants: combos.map((values, index) => old.get(optionKey(values)) || { sku: `${prefix}-${values.map((value) => cleanSku(value.value_slug)).join('-') || index + 1}`, option_values: values, stock: 0, base_price: '', sale_price: '', image_asset_ids: [] }) })); setError('')
  }
  const addFiles = (event) => { const files = Array.from(event.target.files || []); if (images.length + files.length > 30) return setError('Tối đa 30 ảnh cho mỗi sản phẩm'); const start = images.filter((image) => image.type === 'new').length; const added = files.map((file, index) => ({ type: 'new', id: `new:${start + index}`, file, url: URL.createObjectURL(file) })); setImages((current) => [...current, ...added]); setGallery((current) => [...current, ...added.slice(0, Math.max(0, 5 - current.length)).map((image) => image.id)]); event.target.value = '' }
  const removeImage = (image) => { const ref = image.id; setImages((current) => current.filter((item) => item !== image)); setGallery((current) => current.filter((id) => id !== ref)); setForm((current) => ({ ...current, variants: current.variants.map((variant) => ({ ...variant, image_asset_ids: variant.image_asset_ids.filter((id) => id !== ref) })) })) }
  const toggleGallery = (ref) => setGallery((current) => current.includes(ref) ? current.filter((id) => id !== ref) : current.length < 5 ? [...current, ref] : current)
  const updateVariant = (index, key, value) => setForm((current) => ({ ...current, variants: current.variants.map((variant, position) => position === index ? { ...variant, [key]: value } : variant) }))
  const toggleVariantImage = (index, ref) => setForm((current) => ({ ...current, variants: current.variants.map((variant, position) => position !== index ? variant : { ...variant, image_asset_ids: variant.image_asset_ids.includes(ref) ? variant.image_asset_ids.filter((id) => id !== ref) : variant.image_asset_ids.length < 5 ? [...variant.image_asset_ids, ref] : variant.image_asset_ids }) }))
  const submit = async (event) => { event.preventDefault(); setError(''); if (!images.length || !gallery.length) return setError('Sản phẩm cần ảnh và ít nhất một ảnh gallery'); setBusy(true); try { let next = 0; const refMap = new Map(); const media_manifest = images.map((image) => { if (image.type === 'new') { const ref = `new:${next}`; refMap.set(image.id, ref); return { type: 'new', index: next++ } } refMap.set(image.id, image.id); return { type: 'existing', id: image.id } }); const resolve = (refs) => refs.map((ref) => refMap.get(ref)).filter(Boolean); const payload = { ...form, base_price: Number(form.base_price), sale_price: form.sale_price === '' ? null : Number(form.sale_price), gallery_asset_ids: resolve(gallery), variants: form.variants.map((variant) => ({ ...variant, image_asset_ids: resolve(variant.image_asset_ids), stock: Number(variant.stock), base_price: variant.base_price === '' ? null : Number(variant.base_price), sale_price: variant.sale_price === '' ? null : Number(variant.sale_price) })), media_manifest }; onSaved(await saveAdminProduct(product?._id, payload, newFiles)) } catch (requestError) { setError(requestError.response?.data?.message || 'Không thể lưu sản phẩm') } finally { setBusy(false) } }
  const count = form.option_axes.reduce((total, axis) => total * Math.max(1, axis.value_ids.length), form.option_axes.length ? 1 : 0)
  return <div className='fixed inset-0 z-[100] bg-black/60'><form onSubmit={submit} className='absolute inset-y-0 right-0 w-full max-w-5xl overflow-y-auto bg-[#f5f5f2]'><header className='sticky top-0 z-20 flex items-center justify-between border-b bg-white px-6 py-4'><h2 className='text-xl font-black uppercase'>{product ? 'Chỉnh sửa' : 'Tạo'} sản phẩm</h2><button type='button' onClick={onClose} className='border p-2'><X/></button></header><div className='space-y-5 p-6'>{error && <div className='border border-red-300 bg-red-50 p-3 text-sm text-red-700'>{error}</div>}
    <section className='grid gap-4 bg-white p-5 md:grid-cols-2'><label className='text-xs font-bold md:col-span-2'>Tên<input required value={form.name} onChange={field('name')} className='mt-2 w-full border p-3'/></label><label className='text-xs font-bold'>Danh mục<select required value={form.category_id} onChange={field('category_id')} className='mt-2 w-full border bg-white p-3'><option value=''>Chọn danh mục</option>{categories.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label className='text-xs font-bold'>Thương hiệu<select required value={form.brand_id} onChange={field('brand_id')} className='mt-2 w-full border bg-white p-3'><option value=''>Chọn thương hiệu</option>{brands.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label className='text-xs font-bold'>Giá chung<input required type='number' min='0' value={form.base_price} onChange={field('base_price')} className='mt-2 w-full border p-3'/></label><label className='text-xs font-bold'>Giá KM chung<input type='number' min='0' value={form.sale_price} onChange={field('sale_price')} className='mt-2 w-full border p-3'/></label><label className='text-xs font-bold md:col-span-2'>Mô tả<textarea value={form.description} onChange={field('description')} className='mt-2 min-h-28 w-full border p-3'/></label></section>
    <section className='bg-white p-5'><div className='flex items-center justify-between'><div><h3 className='text-xs font-black uppercase'>Thư viện ảnh ({images.length}/30)</h3><p className='text-xs text-neutral-500'>Bấm ảnh để chọn gallery chính, tối đa 5 ảnh.</p></div><label className='cursor-pointer bg-black px-4 py-3 text-xs font-bold text-white'><ImagePlus className='mr-2 inline h-4 w-4'/>Tải ảnh<input type='file' multiple accept='image/jpeg,image/png,image/webp' onChange={addFiles} className='hidden'/></label></div><div className='mt-4 grid grid-cols-4 gap-3 md:grid-cols-8'>{images.map((image) => { const ref = image.id; return <div key={ref} className={`relative aspect-square border-2 ${gallery.includes(ref) ? 'border-black' : 'border-transparent'}`}><button type='button' onClick={() => toggleGallery(ref)} className='h-full w-full'><img src={image.url} alt='' className='h-full w-full object-cover'/></button><button type='button' onClick={() => removeImage(image)} className='absolute right-0 top-0 bg-red-700 p-1 text-white'><Trash2 className='h-3 w-3'/></button></div>})}</div></section>
    <section className='bg-white p-5'><div className='flex flex-wrap items-center justify-between gap-3'><div><h3 className='text-xs font-black uppercase'>Nhóm thuộc tính ({form.option_axes.length}/4)</h3><p className='text-xs text-neutral-500'>{count} tổ hợp dự kiến · tối đa 100</p></div><div className='flex gap-2'><button type='button' disabled={form.option_axes.length >= 4} onClick={() => setForm((current) => ({ ...current, option_axes: [...current.option_axes, { attribute_id: '', value_ids: [] }] }))} className='border px-3 py-2 text-xs font-bold'><Plus className='mr-1 inline h-4 w-4'/>Nhóm</button><button type='button' onClick={generate} className='bg-black px-3 py-2 text-xs font-bold text-white'>Sinh tổ hợp</button></div></div><div className='mt-4 space-y-4'>{form.option_axes.map((axis, index) => { const attribute = attributes.find((item) => item._id === axis.attribute_id); return <div key={index} className='border p-4'><div className='flex gap-2'><select value={axis.attribute_id} onChange={(event) => setAxisAttribute(index, event.target.value)} className='flex-1 border p-2'><option value=''>Chọn nhóm</option>{attributes.filter((item) => !form.option_axes.some((other, position) => position !== index && other.attribute_id === item._id)).map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select><button type='button' onClick={() => setForm((current) => ({ ...current, option_axes: current.option_axes.filter((_, position) => position !== index) }))} className='text-red-700'><Trash2/></button></div><div className='mt-3 flex flex-wrap gap-2'>{attribute?.values.map((value) => <button type='button' key={value._id} onClick={() => toggleAxisValue(index, value._id)} className={`border px-3 py-2 text-xs ${axis.value_ids.includes(value._id) ? 'bg-black text-white' : ''}`}>{value.name}</button>)}</div></div>})}</div></section>
    <section className='bg-white p-5'><h3 className='text-xs font-black uppercase'>SKU ({form.variants.length}/100)</h3><div className='mt-4 space-y-3'>{form.variants.map((variant, index) => <div key={optionKey(variant.option_values) || index} className='border p-4'><p className='mb-3 text-xs font-bold'>{variant.option_values.map((value) => `${value.value_name}`).join(' / ') || `${variant.color} / ${variant.size}`}</p><div className='grid gap-2 md:grid-cols-4'><input required value={variant.sku} onChange={(event) => updateVariant(index, 'sku', event.target.value)} placeholder='SKU' className='border p-2 uppercase'/><input required type='number' min='0' value={variant.stock} onChange={(event) => updateVariant(index, 'stock', event.target.value)} placeholder='Tồn kho' className='border p-2'/><input type='number' min='0' value={variant.base_price} onChange={(event) => updateVariant(index, 'base_price', event.target.value)} placeholder='Giá riêng (tùy chọn)' className='border p-2'/><input type='number' min='0' value={variant.sale_price} onChange={(event) => updateVariant(index, 'sale_price', event.target.value)} placeholder='Giá KM riêng' className='border p-2'/></div><div className='mt-3 flex gap-2 overflow-x-auto'>{images.map((image) => <button type='button' key={image.id} onClick={() => toggleVariantImage(index, image.id)} className={`h-12 w-12 shrink-0 border-2 ${variant.image_asset_ids.includes(image.id) ? 'border-black' : 'border-transparent'}`}><img src={image.url} alt='' className='h-full w-full object-cover'/></button>)}</div></div>)}</div></section>
    <label className='flex items-center justify-between bg-white p-5 text-xs font-black uppercase'>Bật kinh doanh<input type='checkbox' checked={form.business_enabled} onChange={field('business_enabled')} className='h-5 w-5'/></label><div className='sticky bottom-0 flex gap-3 bg-[#f5f5f2] py-4'><button type='button' onClick={onClose} className='flex-1 border bg-white py-4'>Hủy</button><button disabled={busy} className='flex-[2] bg-black py-4 font-bold text-white disabled:opacity-50'>{busy ? 'Đang lưu...' : 'Lưu sản phẩm'}</button></div></div></form></div>
}
