import { Pencil, Plus, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { addAdminAttributeValue, createAdminAttribute, listAdminAttributes, trashAdminAttribute, trashAdminAttributeValue, updateAdminAttribute, updateAdminAttributeValue } from '../../services/adminProductApi.js'

const messageOf = (error) => error.response?.data?.message || 'Không thể xử lý thuộc tính'
export default function ManageAttributes() {
  const [rows, setRows] = useState([]), [editing, setEditing] = useState(undefined), [valueEdit, setValueEdit] = useState(null), [form, setForm] = useState({ name: '', display_type: 'text' })
  const load = useCallback(() => listAdminAttributes({ limit: 100 }).then((result) => setRows(result.data || [])).catch((error) => toast.error(messageOf(error))), [])
  useEffect(() => { load() }, [load])
  const saveAttribute = async (event) => { event.preventDefault(); try { editing?._id ? await updateAdminAttribute(editing._id, form) : await createAdminAttribute(form); setEditing(undefined); load() } catch (error) { toast.error(messageOf(error)) } }
  const saveValue = async (event) => { event.preventDefault(); try { const payload = { name: valueEdit.name, color_hex: valueEdit.color_hex || null }; valueEdit._id ? await updateAdminAttributeValue(valueEdit.attribute._id, valueEdit._id, payload) : await addAdminAttributeValue(valueEdit.attribute._id, payload); setValueEdit(null); load() } catch (error) { toast.error(messageOf(error)) } }
  return <section className='px-4 py-8 lg:px-8'><div className='mx-auto max-w-[1200px]'><header className='flex items-end justify-between border-b border-black pb-6'><div><p className='text-xs font-bold uppercase tracking-[.25em] text-neutral-500'>Biến thể dùng chung</p><h1 className='mt-2 text-4xl font-black uppercase'>Thuộc tính</h1></div><button onClick={() => { setEditing({}); setForm({ name: '', display_type: 'text' }) }} className='flex items-center gap-2 bg-black px-5 py-3 text-xs font-black uppercase text-white'><Plus className='h-4 w-4'/>Thêm nhóm</button></header>
    <div className='mt-5 grid gap-5 lg:grid-cols-2'>{rows.map((row) => <article key={row._id} className='bg-white p-5'><div className='flex items-start justify-between'><div><h2 className='text-lg font-black uppercase'>{row.name}</h2><p className='text-xs text-neutral-500'>/{row.slug} · {row.display_type === 'color' ? 'Màu sắc' : 'Văn bản'} · {row.product_count} sản phẩm</p></div><div className='flex gap-2'><button onClick={() => { setEditing(row); setForm({ name: row.name, display_type: row.display_type }) }} className='border p-2'><Pencil className='h-4 w-4'/></button><button disabled={row.product_count > 0} onClick={() => confirm(`Xóa “${row.name}”?`) && trashAdminAttribute(row._id).then(load).catch((error) => toast.error(messageOf(error)))} className='border p-2 text-red-700 disabled:opacity-30'><Trash2 className='h-4 w-4'/></button></div></div><div className='mt-5 flex flex-wrap gap-2'>{row.values.map((value) => <button key={value._id} onClick={() => setValueEdit({ ...value, attribute: row })} className='flex items-center gap-2 border px-3 py-2 text-xs'>{value.color_hex && <span className='h-4 w-4 rounded-full border' style={{ backgroundColor: value.color_hex }}/>} {value.name}</button>)}<button onClick={() => setValueEdit({ attribute: row, name: '', color_hex: '' })} className='border border-dashed px-3 py-2 text-xs font-bold'>+ Giá trị</button></div></article>)}</div>
  </div>{editing !== undefined && <div className='fixed inset-0 z-[100] bg-black/60'><form onSubmit={saveAttribute} className='absolute inset-y-0 right-0 w-full max-w-md bg-white p-8'><h2 className='text-2xl font-black uppercase'>Nhóm thuộc tính</h2><input autoFocus required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder='Ví dụ: Chất liệu' className='mt-8 w-full border p-3'/><select value={form.display_type} onChange={(event) => setForm({ ...form, display_type: event.target.value })} className='mt-4 w-full border bg-white p-3'><option value='text'>Văn bản</option><option value='color'>Màu sắc</option></select><div className='mt-6 flex gap-3'><button type='button' onClick={() => setEditing(undefined)} className='flex-1 border p-3'>Hủy</button><button className='flex-1 bg-black p-3 text-white'>Lưu</button></div></form></div>}
    {valueEdit && <div className='fixed inset-0 z-[110] bg-black/60'><form onSubmit={saveValue} className='absolute inset-y-0 right-0 w-full max-w-md bg-white p-8'><h2 className='text-2xl font-black uppercase'>Giá trị {valueEdit.attribute.name}</h2><input autoFocus required value={valueEdit.name} onChange={(event) => setValueEdit({ ...valueEdit, name: event.target.value })} placeholder='Tên giá trị' className='mt-8 w-full border p-3'/>{valueEdit.attribute.display_type === 'color' && <input type='color' value={valueEdit.color_hex || '#000000'} onChange={(event) => setValueEdit({ ...valueEdit, color_hex: event.target.value })} className='mt-4 h-12 w-full border p-1'/>}<div className='mt-6 flex gap-3'><button type='button' onClick={() => setValueEdit(null)} className='flex-1 border p-3'>Hủy</button>{valueEdit._id && <button type='button' onClick={() => confirm('Xóa giá trị này?') && trashAdminAttributeValue(valueEdit.attribute._id, valueEdit._id).then(() => { setValueEdit(null); load() }).catch((error) => toast.error(messageOf(error)))} className='border border-red-700 px-4 text-red-700'>Xóa</button>}<button className='flex-1 bg-black p-3 text-white'>Lưu</button></div></form></div>}</section>
}
