import { ChevronLeft, ChevronRight, Pencil, Plus, RefreshCw, RotateCcw, Search, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { createAdminCategory, listAdminCategories, purgeAdminCategory, restoreAdminCategory, trashAdminCategory, updateAdminCategory } from '../../services/adminProductApi.js'

const messageOf = (error) => error.response?.data?.message || 'Không thể xử lý yêu cầu'

export default function ManageCategories() {
  const [rows, setRows] = useState([]); const [page, setPage] = useState(1); const [pagination, setPagination] = useState({ total: 0, totalPages: 1 })
  const [trash, setTrash] = useState(false); const [searchInput, setSearchInput] = useState(''); const [search, setSearch] = useState('')
  const [editing, setEditing] = useState(null); const [form, setForm] = useState({ name: '', description: '' }); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { const result = await listAdminCategories({ page, limit: 10, trash, search: search || undefined }); setRows(result.data || []); setPagination(result.pagination || { total: 0, totalPages: 1 }) } catch (error) { toast.error(messageOf(error)) } finally { setLoading(false) } }, [page, search, trash])
  useEffect(() => { load() }, [load])
  const open = (category) => { setEditing(category || {}); setForm(category ? { name: category.name, description: category.description || '' } : { name: '', description: '' }) }
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { if (editing?._id) await updateAdminCategory(editing._id, form); else await createAdminCategory(form); toast.success(editing?._id ? 'Đã cập nhật danh mục' : 'Đã tạo danh mục'); setEditing(null); await load() } catch (error) { toast.error(messageOf(error)) } finally { setBusy(false) } }
  const remove = async (row, permanent = false) => { if (!window.confirm(permanent ? `Xóa vĩnh viễn danh mục “${row.name}”?` : `Chuyển “${row.name}” vào thùng rác?`)) return; try { if (permanent) await purgeAdminCategory(row._id); else await trashAdminCategory(row._id); toast.success('Đã xử lý danh mục'); await load() } catch (error) { toast.error(messageOf(error)) } }
  const restore = async (row) => { try { await restoreAdminCategory(row._id); toast.success('Đã khôi phục danh mục'); await load() } catch (error) { toast.error(messageOf(error)) } }
  return <section className='px-4 py-8 lg:px-8'><div className='mx-auto max-w-[1360px]'>
    <div className='flex flex-col justify-between gap-5 border-b border-black pb-6 sm:flex-row sm:items-end'><div><p className='text-xs font-bold uppercase tracking-[.25em] text-neutral-500'>Cấu trúc cửa hàng</p><h1 className='mt-2 text-3xl font-black uppercase sm:text-5xl'>Quản lý danh mục</h1></div><button onClick={() => open(null)} className='flex items-center justify-center gap-2 bg-black px-5 py-3 text-xs font-black uppercase text-white'><Plus className='h-4 w-4' />Thêm danh mục</button></div>
    <div className='mt-5 flex flex-col gap-3 bg-white p-4 sm:flex-row'><form onSubmit={(event) => { event.preventDefault(); setSearch(searchInput.trim()); setPage(1) }} className='flex flex-1 border'><Search className='ml-3 mt-3 h-4 w-4'/><input value={searchInput} onChange={(event) => setSearchInput(event.target.value)} className='min-w-0 flex-1 px-3 outline-none' placeholder='Tìm tên danh mục...'/><button className='bg-black px-4 text-xs font-black uppercase text-white'>Tìm</button></form><button onClick={() => { setTrash((value) => !value); setPage(1) }} className={`px-4 py-3 text-xs font-black uppercase ${trash ? 'bg-red-700 text-white' : 'border'}`}>{trash ? 'Đang xem thùng rác' : 'Thùng rác'}</button><button onClick={load} className='border p-3'><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`}/></button></div>
    <div className='mt-5 overflow-x-auto bg-white'><table className='w-full min-w-[760px] text-left text-sm'><thead className='border-b bg-neutral-50 text-[10px] font-black uppercase'><tr><th className='p-4'>Danh mục</th><th className='p-4'>Mô tả</th><th className='p-4'>Sản phẩm</th><th className='p-4 text-right'>Thao tác</th></tr></thead><tbody className='divide-y'>{loading ? <tr><td colSpan='4' className='p-12 text-center'>Đang tải...</td></tr> : !rows.length ? <tr><td colSpan='4' className='p-12 text-center text-neutral-500'>Không có danh mục</td></tr> : rows.map((row) => <tr key={row._id}><td className='p-4'><b>{row.name}</b><p className='text-xs text-neutral-400'>/{row.slug}</p></td><td className='max-w-md p-4 text-neutral-600'>{row.description || '—'}</td><td className='p-4 font-bold'>{row.product_count}</td><td className='p-4'><div className='flex justify-end gap-2'>{trash ? <><button onClick={() => restore(row)} className='border p-2' title='Khôi phục'><RotateCcw className='h-4 w-4'/></button><button onClick={() => remove(row, true)} className='bg-red-700 p-2 text-white' title='Xóa vĩnh viễn'><Trash2 className='h-4 w-4'/></button></> : <><button onClick={() => open(row)} className='border p-2'><Pencil className='h-4 w-4'/></button><button disabled={row.product_count > 0} onClick={() => remove(row)} className='border p-2 text-red-700 disabled:opacity-30'><Trash2 className='h-4 w-4'/></button></>}</div></td></tr>)}</tbody></table></div>
    {pagination.totalPages > 1 && <div className='mt-6 flex items-center justify-center gap-4'><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className='bg-white p-2 disabled:opacity-30'><ChevronLeft/></button><b className='text-xs'>Trang {page}/{pagination.totalPages}</b><button disabled={page >= pagination.totalPages} onClick={() => setPage((value) => value + 1)} className='bg-white p-2 disabled:opacity-30'><ChevronRight/></button></div>}
  </div>{editing && <div className='admin-drawer-backdrop fixed inset-0 z-[100] bg-black/55' onMouseDown={(event) => event.target === event.currentTarget && !busy && setEditing(null)}><form onSubmit={submit} className='admin-drawer-panel absolute inset-y-0 right-0 w-full max-w-lg overflow-y-auto bg-white p-6 sm:p-8'><div className='flex items-center justify-between'><h2 className='text-2xl font-black uppercase'>{editing._id ? 'Sửa danh mục' : 'Thêm danh mục'}</h2><button type='button' onClick={() => setEditing(null)}>Đóng</button></div><label className='mt-8 block text-xs font-black uppercase'>Tên danh mục<input autoFocus value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className='mt-2 w-full border p-3 text-sm font-normal normal-case' required minLength='2'/></label><label className='mt-5 block text-xs font-black uppercase'>Mô tả<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className='mt-2 min-h-32 w-full border p-3 text-sm font-normal normal-case'/></label><button disabled={busy} className='mt-8 w-full bg-black py-4 text-xs font-black uppercase text-white disabled:opacity-50'>{busy ? 'Đang lưu...' : 'Lưu danh mục'}</button></form></div>}</section>
}
