import { Pencil, Plus, RotateCcw, Search, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { createAdminBrand, listAdminBrands, purgeAdminBrand, restoreAdminBrand, trashAdminBrand, updateAdminBrand } from '../../services/adminProductApi.js'

const messageOf = (error) => error.response?.data?.message || 'Không thể xử lý thương hiệu'
export default function ManageBrands() {
  const [rows, setRows] = useState([]), [search, setSearch] = useState(''), [trash, setTrash] = useState(false), [editing, setEditing] = useState(undefined), [form, setForm] = useState({ name: '', description: '' })
  const load = useCallback(() => listAdminBrands({ limit: 100, search: search || undefined, trash }).then((result) => setRows(result.data || [])).catch((error) => toast.error(messageOf(error))), [search, trash])
  useEffect(() => { load() }, [load])
  const open = (row = null) => { setEditing(row); setForm({ name: row?.name || '', description: row?.description || '' }) }
  const submit = async (event) => { event.preventDefault(); try { editing?._id ? await updateAdminBrand(editing._id, form) : await createAdminBrand(form); toast.success('Đã lưu thương hiệu'); setEditing(undefined); load() } catch (error) { toast.error(messageOf(error)) } }
  const remove = async (row, permanent) => { if (!confirm(`${permanent ? 'Xóa vĩnh viễn' : 'Chuyển vào thùng rác'} “${row.name}”?`)) return; try { permanent ? await purgeAdminBrand(row._id) : await trashAdminBrand(row._id); load() } catch (error) { toast.error(messageOf(error)) } }
  return <section className='px-4 py-8 lg:px-8'><div className='mx-auto max-w-[1200px]'><header className='flex items-end justify-between border-b border-black pb-6'><div><p className='text-xs font-bold uppercase tracking-[.25em] text-neutral-500'>Danh mục hàng hóa</p><h1 className='mt-2 text-4xl font-black uppercase'>Thương hiệu</h1></div><button onClick={() => open()} className='flex items-center gap-2 bg-black px-5 py-3 text-xs font-black uppercase text-white'><Plus className='h-4 w-4'/>Thêm thương hiệu</button></header>
    <div className='mt-5 flex gap-3 bg-white p-4'><label className='flex flex-1 items-center border px-3'><Search className='h-4 w-4'/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder='Tìm thương hiệu...' className='w-full p-3 outline-none'/></label><button onClick={() => setTrash(!trash)} className={`px-4 text-xs font-black uppercase ${trash ? 'bg-red-700 text-white' : 'border'}`}>{trash ? 'Đang xem thùng rác' : 'Thùng rác'}</button></div>
    <div className='mt-5 divide-y bg-white'>{rows.map((row) => <article key={row._id} className='flex items-center gap-4 p-5'><div className='min-w-0 flex-1'><div className='flex items-center gap-2'><b>{row.name}</b>{row.is_system && <span className='bg-neutral-200 px-2 py-1 text-[9px] font-bold uppercase'>Hệ thống</span>}</div><p className='text-xs text-neutral-500'>/{row.slug} · {row.product_count} sản phẩm</p><p className='mt-1 text-sm text-neutral-600'>{row.description}</p></div><div className='flex gap-2'>{trash ? <><button onClick={() => restoreAdminBrand(row._id).then(load)} className='border p-2'><RotateCcw className='h-4 w-4'/></button><button onClick={() => remove(row, true)} className='bg-red-700 p-2 text-white'><Trash2 className='h-4 w-4'/></button></> : <><button onClick={() => open(row)} className='border p-2'><Pencil className='h-4 w-4'/></button><button disabled={row.is_system || row.product_count > 0} onClick={() => remove(row)} className='border p-2 text-red-700 disabled:opacity-30'><Trash2 className='h-4 w-4'/></button></>}</div></article>)}</div>
  </div>{editing !== undefined && <div className='fixed inset-0 z-[100] bg-black/60'><form onSubmit={submit} className='absolute inset-y-0 right-0 w-full max-w-lg bg-white p-8'><h2 className='text-2xl font-black uppercase'>{editing?._id ? 'Sửa' : 'Thêm'} thương hiệu</h2><label className='mt-8 block text-xs font-bold uppercase'>Tên<input autoFocus required minLength='2' value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className='mt-2 w-full border p-3 normal-case'/></label><label className='mt-5 block text-xs font-bold uppercase'>Mô tả<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className='mt-2 min-h-32 w-full border p-3 normal-case'/></label><div className='mt-8 flex gap-3'><button type='button' onClick={() => setEditing(undefined)} className='flex-1 border py-3'>Hủy</button><button className='flex-1 bg-black py-3 text-white'>Lưu</button></div></form></div>}</section>
}
