import { useEffect, useMemo, useRef, useState } from 'react'
import { ChevronLeft, ChevronRight, Search, SlidersHorizontal, Sparkles, X } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import FavoriteButton from '../../components/FavoriteButton.jsx'
import { getProductFacets, getProducts, searchProducts } from '../../services/productApi.js'
import { formatCurrency } from '../../utils/formatCurrency.js'

const LIMIT = 12
const FALLBACK_IMAGE = `data:image/svg+xml,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="600" height="800"><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="Arial" font-size="28" fill="#777">AESTHETIX</text></svg>')}`
const SUGGESTIONS = ['Áo chống nắng UPF 50+', 'Đồ bơi đi biển', 'Sơ mi lụa công sở', 'Set đồ tập gym yoga']
const list = (params, key) => (params.get(key) || '').split(',').filter(Boolean)
const paramsObject = (params) => Object.fromEntries([...params.entries()].filter(([, value]) => value !== ''))

function ProductCard({ product }) {
  const price = product.min_price ?? product.sale_price ?? product.base_price
  const maxPrice = product.max_price ?? price
  const sale = product.sale_price != null && product.sale_price < product.base_price && maxPrice === price
  const discount = sale ? Math.round((1 - product.sale_price / product.base_price) * 100) : 0
  return <article className='group min-w-0'>
    <div className='relative aspect-[3/4] overflow-hidden bg-neutral-100'>
      <Link to={`/products/${product._id}`} className='block h-full' aria-label={`Xem ${product.name}`}>
        <img src={product.images?.[0] || FALLBACK_IMAGE} alt={product.name} loading='lazy' onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = FALLBACK_IMAGE }} className='h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]' />
      </Link>
      {sale && <span className='absolute left-3 top-3 bg-black px-2.5 py-1.5 text-[10px] font-bold uppercase tracking-wider text-white'>-{discount}%</span>}
      <FavoriteButton product={product} className='absolute right-3 top-3 z-10' />
    </div>
    <Link to={`/products/${product._id}`} className='block border-t border-neutral-200 pt-3'>
      <div className='flex items-start justify-between gap-2 text-[10px] font-bold uppercase tracking-[0.14em] text-neutral-500'><span>{product.brand || 'AESTHETIX'}</span><span className='text-right'>{product.category_id?.name || ''}</span></div>
      <h2 className='mt-2 min-h-10 text-sm font-semibold leading-5 group-hover:underline'>{product.name}</h2>
      <div className='mt-2 flex flex-wrap items-baseline gap-2'><strong className='font-mono text-sm'>{maxPrice > price ? `${formatCurrency(price)} – ${formatCurrency(maxPrice)}` : formatCurrency(price)}</strong>{sale && <span className='font-mono text-xs text-neutral-400 line-through'>{formatCurrency(product.base_price)}</span>}</div>
    </Link>
  </article>
}

function Skeleton() { return <div className='animate-pulse'><div className='aspect-[3/4] bg-neutral-200' /><div className='mt-3 h-3 bg-neutral-200' /><div className='mt-3 h-5 bg-neutral-200' /></div> }

function CheckList({ items = [], selected = [], onToggle, getLabel = (item) => item, getValue = (item) => item }) {
  return <div className='space-y-2'>{items.filter(Boolean).map((item) => { const value = getValue(item); return <label key={value} className='flex cursor-pointer items-center justify-between gap-3 text-sm'><span className='flex min-w-0 items-center gap-2'><input type='checkbox' checked={selected.includes(value)} onChange={() => onToggle(value)} className='h-4 w-4 accent-black' /><span className='truncate'>{getLabel(item)}</span></span>{item.count != null && <span className='font-mono text-xs text-neutral-400'>{item.count}</span>}</label> })}</div>
}

function FilterPanel({ facets, params, update, clearAll, mobile = false }) {
  const [categoryQuery, setCategoryQuery] = useState('')
  const categories = list(params, 'categories'); const brands = list(params, 'brands')
  const toggle = (key, value) => { const current = list(params, key); update(key, current.includes(value) ? current.filter((item) => item !== value).join(',') : [...current, value].join(',')) }
  const visibleCategories = facets.categories.filter((item) => item.name.toLowerCase().includes(categoryQuery.toLowerCase()))
  return <div className={mobile ? 'pb-28' : ''}>
    <div className='flex items-end justify-between border-b border-black pb-4'><div><h2 className='text-xl font-bold uppercase'>Bộ lọc</h2><p className='mt-1 text-[10px] font-bold uppercase tracking-widest text-neutral-500'>Tinh chỉnh lựa chọn</p></div><button type='button' onClick={clearAll} className='text-xs font-bold uppercase underline'>Xóa tất cả</button></div>
    <section className='border-b py-5'><h3 className='mb-3 text-xs font-bold uppercase tracking-widest'>Danh mục</h3><label className='mb-3 flex items-center gap-2 border border-neutral-300 px-3 py-2'><Search className='h-4 w-4' /><input value={categoryQuery} onChange={(event) => setCategoryQuery(event.target.value)} placeholder='Tìm danh mục' className='min-w-0 flex-1 bg-transparent text-sm outline-none' /></label><div className='custom-scrollbar max-h-64 overflow-y-auto pr-2'><CheckList items={visibleCategories} selected={categories} onToggle={(value) => toggle('categories', value)} getLabel={(item) => item.name} getValue={(item) => item.slug} /></div></section>
    <section className='border-b py-5'><h3 className='mb-3 text-xs font-bold uppercase tracking-widest'>Thương hiệu</h3><div className='custom-scrollbar max-h-48 overflow-y-auto pr-2'><CheckList items={facets.brands} selected={brands} onToggle={(value) => toggle('brands', value)} getLabel={(item) => item.name} getValue={(item) => item.name} /></div></section>
    {(facets.attributes || []).map((attribute) => { const key = `attr.${attribute.slug}`; const selected = list(params, key); return <section key={attribute._id} className='border-b py-5'><h3 className='mb-3 text-xs font-bold uppercase tracking-widest'>{attribute.name}</h3><div className='flex flex-wrap gap-2'>{attribute.values.map((value) => <button type='button' key={value._id} onClick={() => toggle(key, value.slug)} className={`flex items-center gap-2 border px-3 py-2 text-xs ${selected.includes(value.slug) ? 'border-black bg-black text-white' : 'border-neutral-300'}`}>{value.color_hex && <span className='h-3.5 w-3.5 rounded-full border' style={{ backgroundColor: value.color_hex }}/>} {value.name}</button>)}</div></section> })}
    <section className='py-5'><h3 className='mb-3 text-xs font-bold uppercase tracking-widest'>Khoảng giá (VND)</h3><div className='grid grid-cols-2 gap-2'><label className='text-[10px] uppercase text-neutral-500'>Từ<input type='number' min='0' step='50000' value={params.get('minPrice') || ''} onChange={(event) => update('minPrice', event.target.value)} placeholder={String(facets.price.min || 0)} className='mt-1 w-full border border-neutral-300 px-3 py-2 text-sm text-black outline-none focus:border-black' /></label><label className='text-[10px] uppercase text-neutral-500'>Đến<input type='number' min='0' step='50000' value={params.get('maxPrice') || ''} onChange={(event) => update('maxPrice', event.target.value)} placeholder={String(facets.price.max || 0)} className='mt-1 w-full border border-neutral-300 px-3 py-2 text-sm text-black outline-none focus:border-black' /></label></div></section>
  </div>
}

export default function CatalogPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const signature = searchParams.toString()
  const [queryInput, setQueryInput] = useState(searchParams.get('q') || '')
  const [products, setProducts] = useState([]); const [meta, setMeta] = useState({ total_items: 0, current_page: 1, total_pages: 0 })
  const [facets, setFacets] = useState({ categories: [], brands: [], attributes: [], sizes: [], colors: [], price: { min: 0, max: 0 } })
  const [mode, setMode] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [drawer, setDrawer] = useState(false)
  const closeRef = useRef(null)
  const dialogRef = useRef(null)

  const replace = (changes, resetPage = true) => { const next = new URLSearchParams(searchParams); Object.entries(changes).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); if (resetPage) next.delete('page'); setSearchParams(next) }
  const update = (key, value) => replace({ [key]: value })
  const clearAll = () => { const q = searchParams.get('q'); const next = new URLSearchParams(); if (q) next.set('q', q); setSearchParams(next) }
  const load = async () => { setLoading(true); setError(''); try { const requestParams = { ...paramsObject(searchParams), limit: LIMIT }; const response = requestParams.q ? await searchProducts(requestParams) : await getProducts(requestParams); setProducts(response.data.data || []); setMeta(response.data.meta || {}); setMode(response.data.search_mode || null) } catch (requestError) { setError(requestError.response?.data?.message || 'Không thể tải bộ sưu tập.') } finally { setLoading(false) } }

  useEffect(() => { getProductFacets().then(({ data }) => setFacets(data.data)).catch(() => {}) }, [])
  useEffect(() => { setQueryInput(searchParams.get('q') || ''); load() }, [signature]) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!drawer) return undefined; const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; closeRef.current?.focus(); const onKey = (event) => { if (event.key === 'Escape') setDrawer(false); if (event.key === 'Tab') { const controls = [...(dialogRef.current?.querySelectorAll('button:not(:disabled), input:not(:disabled), select:not(:disabled), [href]') || [])]; if (!controls.length) return; const first = controls[0]; const last = controls[controls.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() } } }; document.addEventListener('keydown', onKey); return () => { document.body.style.overflow = previous; document.removeEventListener('keydown', onKey) } }, [drawer])

  const activeChips = useMemo(() => { const chips = []; list(searchParams, 'categories').forEach((value) => chips.push({ key: 'categories', value, label: facets.categories.find((item) => item.slug === value)?.name || value, multi: true })); list(searchParams, 'brands').forEach((value) => chips.push({ key: 'brands', value, label: value, multi: true })); facets.attributes.forEach((attribute) => list(searchParams, `attr.${attribute.slug}`).forEach((value) => chips.push({ key: `attr.${attribute.slug}`, value, label: attribute.values.find((item) => item.slug === value)?.name || value, multi: true }))); ['minPrice', 'maxPrice'].forEach((key) => { const value = searchParams.get(key); if (value) chips.push({ key, value, label: key === 'minPrice' ? `Từ ${formatCurrency(Number(value))}` : `Đến ${formatCurrency(Number(value))}` }) }); return chips }, [signature, facets])
  const removeChip = (chip) => chip.multi ? update(chip.key, list(searchParams, chip.key).filter((value) => value !== chip.value).join(',')) : update(chip.key, '')
  const submitSearch = (event) => { event?.preventDefault(); replace({ q: queryInput.trim() }) }
  const page = Number(searchParams.get('page') || 1)
  const goPage = (nextPage) => { replace({ page: String(nextPage) }, false); window.scrollTo({ top: 0, behavior: 'smooth' }) }

  return <main className='bg-[#faf9f7] text-neutral-950'>
    <header className='border-b border-black bg-black text-white'><div className='mx-auto max-w-[1440px] px-4 py-10 sm:px-6 lg:px-8 lg:py-14'><p className='text-[10px] font-bold uppercase tracking-[0.3em] text-neutral-400'>AESTHETIX / Catalog 2026</p><div className='mt-3 grid gap-7 lg:grid-cols-[1fr_1.25fr] lg:items-end'><div><h1 className='text-4xl font-bold uppercase tracking-tight sm:text-6xl'>Bộ sưu tập</h1><p className='mt-3 max-w-md text-sm leading-6 text-neutral-400'>Khám phá catalog thời trang được tuyển chọn theo phong cách, nhu cầu và ngữ cảnh của bạn.</p></div><form onSubmit={submitSearch} className='border border-white/40 bg-white p-2 text-black'><div className='flex items-center gap-2'><Sparkles className='ml-2 h-5 w-5 shrink-0' /><input value={queryInput} onChange={(event) => setQueryInput(event.target.value)} placeholder='Hỏi AI: “trang phục đi biển tối giản”…' aria-label='Tìm kiếm sản phẩm bằng AI' className='min-w-0 flex-1 px-2 py-3 text-sm outline-none sm:text-base' /><button className='bg-black px-5 py-3 text-xs font-bold uppercase text-white'>Tìm kiếm</button></div></form></div><div className='mt-5 flex flex-wrap gap-2'>{SUGGESTIONS.map((suggestion) => <button type='button' key={suggestion} onClick={() => { setQueryInput(suggestion); replace({ q: suggestion }) }} className='border border-white/30 px-3 py-2 text-[10px] uppercase tracking-wider text-neutral-300 hover:border-white hover:text-white'>{suggestion}</button>)}</div></div></header>
    <div className='mx-auto max-w-[1440px] px-4 sm:px-6 lg:px-8'><nav className='custom-scrollbar flex gap-2 overflow-x-auto border-b py-4' aria-label='Danh mục phổ biến'><button type='button' onClick={() => update('categories', '')} className={`shrink-0 border px-4 py-2 text-xs font-bold uppercase ${!searchParams.get('categories') ? 'bg-black text-white' : ''}`}>Tất cả</button>{facets.categories.slice().sort((a, b) => b.count - a.count).slice(0, 8).map((category) => <button type='button' key={category.slug} onClick={() => update('categories', category.slug)} className={`shrink-0 border px-4 py-2 text-xs font-bold uppercase ${list(searchParams, 'categories').includes(category.slug) ? 'bg-black text-white' : ''}`}>{category.name} <span className='ml-1 opacity-50'>{category.count}</span></button>)}</nav>
      <div className='flex items-center justify-between gap-3 border-b py-5'><div><p className='text-sm'><strong>{meta.total_items || 0}</strong> sản phẩm</p>{searchParams.get('q') && <p className='mt-1 text-xs text-neutral-500'>{mode === 'semantic' ? 'AI semantic match' : 'Kết quả từ khóa dự phòng'} cho “{searchParams.get('q')}”</p>}</div><div className='flex items-center gap-2'><button type='button' onClick={() => setDrawer(true)} className='flex items-center gap-2 border border-black px-3 py-2 text-xs font-bold uppercase lg:hidden'><SlidersHorizontal className='h-4 w-4' /> Lọc</button><label className='sr-only' htmlFor='catalog-sort'>Sắp xếp</label><select id='catalog-sort' value={searchParams.get('sort') || 'relevance'} onChange={(event) => update('sort', event.target.value === 'relevance' ? '' : event.target.value)} className='border border-black bg-transparent px-3 py-2 text-xs font-bold uppercase'><option value='relevance'>Liên quan</option><option value='newest'>Mới nhất</option><option value='price_asc'>Giá tăng dần</option><option value='price_desc'>Giá giảm dần</option><option value='name'>Tên A–Z</option></select></div></div>
      {activeChips.length > 0 && <div className='flex flex-wrap items-center gap-2 border-b py-3'>{activeChips.map((chip) => <button type='button' key={`${chip.key}-${chip.value}`} onClick={() => removeChip(chip)} className='flex items-center gap-1 bg-neutral-200 px-3 py-2 text-xs'>{chip.label}<X className='h-3 w-3' /></button>)}<button type='button' onClick={clearAll} className='px-2 text-xs font-bold uppercase underline'>Xóa tất cả</button></div>}
      <div className='grid gap-8 py-8 lg:grid-cols-[240px_minmax(0,1fr)]'><aside className='hidden lg:block'><div className='sticky top-24'><FilterPanel facets={facets} params={searchParams} update={update} clearAll={clearAll} /></div></aside><section aria-live='polite'>{loading ? <div className='grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3 xl:grid-cols-4'>{Array.from({ length: LIMIT }, (_, index) => <Skeleton key={index} />)}</div> : error ? <div className='border border-neutral-300 bg-white px-5 py-20 text-center'><h2 className='text-xl font-bold uppercase'>Không thể tải sản phẩm</h2><p className='mt-3 text-sm text-neutral-500'>{error}</p><button type='button' onClick={load} className='mt-6 bg-black px-6 py-3 text-xs font-bold uppercase text-white'>Thử lại</button></div> : products.length === 0 ? <div className='border border-neutral-300 bg-white px-5 py-20 text-center'><h2 className='text-xl font-bold uppercase'>{searchParams.get('q') ? 'Không có kết quả tìm kiếm' : 'Không có sản phẩm phù hợp'}</h2><p className='mt-3 text-sm text-neutral-500'>Hãy thử từ khóa hoặc bộ lọc khác.</p><button type='button' onClick={clearAll} className='mt-6 bg-black px-6 py-3 text-xs font-bold uppercase text-white'>Xóa bộ lọc</button></div> : <div className='grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3 xl:grid-cols-4'>{products.map((product) => <ProductCard key={product._id} product={product} />)}</div>}
        {!loading && !error && meta.total_pages > 1 && <nav className='mt-14 flex items-center justify-center gap-2' aria-label='Phân trang'><button type='button' disabled={page <= 1} onClick={() => goPage(page - 1)} className='grid h-10 w-10 place-items-center border disabled:opacity-30' aria-label='Trang trước'><ChevronLeft className='h-4 w-4' /></button>{Array.from({ length: meta.total_pages }, (_, index) => index + 1).filter((number) => number === 1 || number === meta.total_pages || Math.abs(number - page) <= 1).map((number, index, visible) => <span key={number} className='contents'>{index > 0 && number - visible[index - 1] > 1 && <span className='px-1'>…</span>}<button type='button' onClick={() => goPage(number)} aria-current={number === page ? 'page' : undefined} className={`h-10 min-w-10 border px-3 text-sm font-bold ${number === page ? 'bg-black text-white' : ''}`}>{number}</button></span>)}<button type='button' disabled={page >= meta.total_pages} onClick={() => goPage(page + 1)} className='grid h-10 w-10 place-items-center border disabled:opacity-30' aria-label='Trang sau'><ChevronRight className='h-4 w-4' /></button></nav>}</section></div></div>
    {drawer && <div className='fixed inset-0 z-50 bg-black/55 lg:hidden' onMouseDown={(event) => { if (event.target === event.currentTarget) setDrawer(false) }}><aside ref={dialogRef} role='dialog' aria-modal='true' aria-label='Bộ lọc sản phẩm' className='absolute inset-y-0 right-0 w-[min(92vw,420px)] overflow-y-auto bg-[#faf9f7] px-5 pt-5 shadow-2xl'><button ref={closeRef} type='button' onClick={() => setDrawer(false)} className='absolute right-4 top-4 grid h-10 w-10 place-items-center' aria-label='Đóng bộ lọc'><X /></button><FilterPanel facets={facets} params={searchParams} update={update} clearAll={clearAll} mobile /><div className='fixed bottom-0 right-0 w-[min(92vw,420px)] border-t bg-white p-4'><button type='button' onClick={() => setDrawer(false)} className='w-full bg-black px-5 py-4 text-xs font-bold uppercase text-white'>Áp dụng · {meta.total_items || 0} sản phẩm</button></div></aside></div>}
  </main>
}
